---
- name: Linux Defaults > Shell > Bash > Aliases > Add Default Aliases
  ansible.builtin.lineinfile:
    dest: "/etc/profile.d/00-ansible-bash-default-aliases.sh"
    create: true
    mode: 0644
    line: 'alias {{ alias.name }}="{{ alias.command }}"'
    regexp: "^alias {{ alias.name }}="
  loop: "{{ default_bash_aliases }}"
  loop_control:
    loop_var: alias
