---
- name: User > Salt > Read Machine-ID
  ansible.builtin.slurp:
    src: /etc/machine-id
  register: machine_id

- name: User > Configure > Root
  ansible.builtin.include_tasks: "user/root.yaml"

- name: User > Configure > Standard
  ansible.builtin.include_tasks: "user/standard.yaml"
  vars:
    - user: "{{ loop_user }}"
  loop: "{{ global_users + host_users }}"
  loop_control:
    loop_var: loop_user
  when: host_users is defined
