---
- name: Linux Defaults > User > Configure > Root > Password
  ansible.builtin.user:
    name: root
    password: "{{ ansible_default_root_pass | password_hash('sha512', machine_id['content'] | b64decode) }}"
  no_log: true

- name: Linux Defaults > User > Configure > Root > .ssh Directory
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    mode: '0700'

- name: Linux Defaults > User > Configure > Root > SSH Keys
  ansible.builtin.openssh_keypair:
    path: "/root/.ssh/id_{{ keytype }}"
    type: "{{ keytype }}"
    state: present
    owner: root
    group: root
    force: false
  loop:
    - "rsa"
    - "dsa"
    - "ecdsa"
    - "ed25519"
  loop_control:
    loop_var: keytype
