---
- name: Linux Defaults > Packages > Debian > APT > Install
  ansible.builtin.apt:
    name: "{{ default_packages | default(packages) }}"
    state: present
    install_recommends: false

- name: Linux Defaults > Packages > Debian > APT > Upgrade
  ansible.builtin.apt:
    upgrade: dist

- name: Linux Defaults > Packages > Debian > APT > Autoremove
  ansible.builtin.apt:
    autoremove: true
