---
- name: Linux Defaults > Packages > Redhat > DNF > Install
  ansible.builtin.dnf:
    name: "{{ default_packages | default(packages) }}"
    state: latest

- name: Linux Defaults > Packages > Redhat > DNF > Upgrade
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Linux Defaults > Packages > Redhat > DNF > Autoremove
  ansible.builtin.dnf:
    autoremove: true
